env:
  TERM: xterm-256color

import:
  - /Users/romanvolkov/.dotfiles/catppuccin/catppuccin-mocha.yml

window:
  dimensions:
    columns: 200
    lines: 60
  padding:
    x: 10
    y: 10
  decorations: buttonless
  opacity: 1
  startup_mode: Windowed
  dynamic_title: true

scrolling:
  history: 30000
  multiplier: 3

font:
  normal:
    family: "FiraCode Nerd Font"
  size: 15

cursor:
  style:
    shape: Block
    blinking: On

live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

key_bindings:
  - { key: F10, action: ToggleFullscreen }
